services:
  database:
    image: postgres:15.3
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=database
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
